### ISSUE TITLE
Missing TRBM_logZperbin_Annealed_Importance_Sampling

### ISSUE THREAD

**Issue by epiasini** [ChrisGll/RBM_TRBM#1]
Hi,

first of all thanks for sharing the code!

I've been playing around with it, and I noticed that the function `TRBM_logZperbin_Annealed_Importance_Sampling` is not defined anywhere, but is called in `TRBM_logZ_Annealed_Importance_Sampling`: https://github.com/ChrisGll/RBM_TRBM/blob/ae0a23f357c55e88b11f31a26e21a1af19595e74/TRBM/TRBM_logZ_Annealed_Importance_Sampling.m#L34

I guess this is not intentional, so you might want to take a look at it.

**Comment by ChrisGll** [comment]
Hello,

Thanks for letting me know about this !

There is actually no such function here, the function is supposed to call itself with the parameter Minv instead of M.

I've fixed this.

**Comment by epiasini** [comment]
Great, thanks!!
